from typing import Protocol


class ResumeCreationStore(Protocol):
    async def resume_queue(self, limit: int, cursor: str | None) -> dict: ...
    async def create_resume(self, application_id: str) -> dict: ...
    def pdf_path(self, resume_id: str): ...
